name: Docker Build and Push

on:
  workflow_dispatch:
  schedule:
    - cron: "12 3 * * 5"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    env:
      FULL_IMAGE_NAME: ${{ vars.REGISTRY_URL }}/${{ vars.REPOSITORY_PATH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: "${{ env.FULL_IMAGE_NAME }}:latest"
          load: true
          push: false

      - name: Extract version from container
        id: get-version
        run: |
          version_output=$(docker run --rm --entrypoint tailscale "${{ env.FULL_IMAGE_NAME }}:latest" version)
          version=$(echo "$version_output" | head -n1 | awk '{$1=$1};1')
          echo "DOCKER_TAG=$version" >> $GITHUB_ENV
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "📦 Extracted version: $version"

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push image
        run: |
          docker tag "$FULL_IMAGE_NAME:latest" "$FULL_IMAGE_NAME:$DOCKER_TAG"
          docker push "$FULL_IMAGE_NAME:latest"
          docker push "$FULL_IMAGE_NAME:$DOCKER_TAG"